#profiles: app
# Mysql database config
#spring:
#  profiles:
#    include: dev

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://172.25.96.1:5432/dev
    username: postgres
    password: 123456
mybatis:
  type-handlers-package: com.example.mybatis.infra
  configuration:
    map-underscore-to-camel-case: true

cloud:
  aws:
    endpoint: http://localhost:4566
    access-key: test
    secret-key: test
    region: ap-northeast-1
    bucket: bucket-name
server:
  error:
    include-message: always
    include-exception: true
    include-binding-errors: always